//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mics_project_v2._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tbl_page
    {
        public int Id { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "Please provide title")]
        public string name { get; set; }

        [AllowHtml]
        [Display(Name = "Content")]
        [Required(ErrorMessage = "Please provide content")]
        public string content { get; set; }

        [Display(Name = "Creater Name")]
        public Nullable<int> admin_id { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
    }
}
