//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mics_project_v2._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDatabaseContext : DbContext
    {
        public HospitalDatabaseContext()
            : base("name=HospitalDatabaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_admin> tbl_admin { get; set; }
        public virtual DbSet<tbl_newsletter> tbl_newsletter { get; set; }
        public virtual DbSet<tbl_primary_nav> tbl_primary_nav { get; set; }
        public virtual DbSet<tbl_volunteer_application> tbl_volunteer_application { get; set; }
        public virtual DbSet<tbl_volunteer_posting> tbl_volunteer_posting { get; set; }
        public virtual DbSet<tbl_page> tbl_page { get; set; }
    }
}
