//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mics_project_v2._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_primary_nav
    {
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> admin_id { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
    }
}
