//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mics_project_v2._1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class tbl_volunteer_posting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_volunteer_posting()
        {
            this.tbl_volunteer_application = new HashSet<tbl_volunteer_application>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Title")]
        [Required(ErrorMessage = "Please provide title")]
        public string title { get; set; }

        [AllowHtml]
        [Display(Name = "Content")]
        [Required(ErrorMessage = "Please provide content")]
        public string content { get; set; }

        [Display(Name = "Date")]
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> admin_id { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_volunteer_application> tbl_volunteer_application { get; set; }
        public virtual tbl_admin tbl_admin1 { get; set; }
    }
}
